run:
  go: '1.19'
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: "github.com/c0dered273/go-adv-metrics"
  gosimple:
    go: "1.19"
#  govet:
#    enable:
#      - fieldalignment

linters:
  enable:
    - contextcheck
    - depguard
    - gofmt
    - gosec
    - bidichk
